# This GitHub action runs your tests for each commit push and/or PR. Optionally
# you can turn it on using a cron schedule for regular testing.
#
name: Tests
on:
  pull_request:
    paths-ignore:
      - "README.md"

  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go mod download

      - name: Build
        env:
          CGO_ENABLED: "0"
        run: |
          go build -v .

      - name: Run integration test (mainline)
        timeout-minutes: 10
        env:
          CODER_IMAGE: "ghcr.io/coder/coder"
        run: |
          source <(go run ./scripts/coderversion)
          CODER_VERSION="${CODER_MAINLINE_VERSION}" go test -v ./integration

      - name: Run integration test (stable)
        timeout-minutes: 10
        env:
          CODER_IMAGE: "ghcr.io/coder/coder"
        run: |
          source <(go run ./scripts/coderversion)
          CODER_VERSION="${CODER_STABLE_VERSION}" go test -v ./integration

  # run acceptance tests in a matrix with Terraform core versions
  test:
    name: Matrix Test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - "1.6.*"
          - "1.7.*"
          - "1.8.*"
          - "1.9.*"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
        id: go

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go mod download

      - name: TF acceptance tests
        timeout-minutes: 10
        env:
          TF_ACC: "1"
        run: |
          go test -v -cover ./provider/

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
        id: go

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "latest"
          terraform_wrapper: false

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go mod download

      - name: Lint fmt
        run: |
          make fmt
          git diff --exit-code

      - name: Lint gen
        run: |
          make gen
          git diff --exit-code
